### ISSUE TITLE
Orde by more than one column in API results

### ISSUE THREAD

**Issue by xzegga** [jasonhinkle/phreeze#140]
Is there any way to order quiery by two or more colums, I need order results first by LocationName and second by Companyname in my query:

domainname.com/phreezeApp/api/companies?Locationid_Equals=&orderAsc=1&orderBy=Companyname&groupBy=

Best!

**Comment by nandoguima** [comment]
> Is there any way to order quiery by two or more colums, I need order results first by LocationName and second by Companyname in my query:
> 
> domainname.com/phreezeApp/api/companies?Locationid_Equals=&orderAsc=1&orderBy=Companyname&groupBy=
> 
> Best!

Hi!

    I have the same problem! Good solution, but where you pass the string "orderBy=locationname&orderByTwo=Companyname" ?

Thanks

**Comment by nandoguima** [comment]
Hi @xzegga 

    I have the same problem! Good solution, but where you pass the string "orderBy=locationname&orderByTwo=Companyname" ?

Thanks
