### ISSUE TITLE
WAMP /phreeze/builder/analyze was not found on this server - I have edited httpd.conf as per instructions

### ISSUE THREAD

**Issue by stemie** [jasonhinkle/phreeze#152]
Hi Jason,

This looks awesome I just wish I could get it to work. It's really driving me nuts.
I have read many of the issue items here and looked at other sites but I still cannot get it to work.

I am running it on WAMP (I also run wordpress on WAMP and it rewrites urls fine)

I changed the following lines in httpd.conf - located here `C:/wamp/bin/apache/apache2.2.22/conf/httpd.conf`

I have removed the `#` from rewrite_module
`LoadModule rewrite_module modules/mod_rewrite.so`

And changed AllowOverride to All
`<Directory "c:/wamp/www/">
    #
    # AllowOverride controls what directives may be placed in .htaccess files.
    # It can be "All", "None", or any combination of the keywords:
    #   Options FileInfo AuthConfig Limit
    #
    AllowOverride All`

I get this message after I click Analyze Database:
Not Found
The requested URL /phreeze/builder/analyze was not found on this server.

The builder page http://localhost/phreeze/builder/ loads fine it just has the error here http://localhost/phreeze/builder/analyze.

Please (for my sanity) can you perhaps enlighten me?

**Comment by andifernandes** [comment]
Do this its working for me!

http://devfuria.com.br/linux/apache-habilitar-mod_rewrite-no-apache-mod/
