### ISSUE TITLE
Edit Form as a view instead of a Modal Popup from list

### ISSUE THREAD

**Issue by diegolaz** [jasonhinkle/phreeze#176]
Is there a way to have the edit forms as a view with parameter (for ID) instead of a modal pop up on the list? Like a direct link to a particular item to edit?

Thanks!

**Comment by jasonhinkle** [comment]
You definitely can build a single record view/form.  The generator doesn't currently build one so you have to write it yourself, but it's not that complicated.  You can get an idea of how to start by checking out the tutorial videos 2 and 3 for routes, controllers and models at http://phreeze.com/phreeze/documentation/videos.php

**Comment by diegolaz** [comment]
thannks! Will try that!
