### ISSUE TITLE
app is not oppening

### ISSUE THREAD

**Issue by maoaa** [jasonhinkle/phreeze#177]
Hello Folks!

I just generated the app and placed on its Application Root Folder as requested.
The file: _machine_config.php is well setup.
When I try to access the app, all I get is a blank page and doesn't show any error message...
Any suggestion?
Thank you!

**Comment by jasonhinkle** [comment]
it sounds like you may have PHP error reporting disabled.  if you can enable that, we should be able to see some kind of output from the app.  Otherwise if your host provider keeps a log of PHP errors you can check there.

**Comment by maoaa** [comment]
Hello Jason,

This is what I got:

PHP Warning:  require_once(verysimple/Authentication/IAuthenticatable.php): failed to open stream: No such file or directory in ../home/cpointco/public_html/clients/texa/cpointcoriver/libs/App/ExampleUser.php on line 5

PHP Fatal error:  require_once(): Failed opening required 'verysimple/Authentication/IAuthenticatable.php' (include_path='/home/cpointco/public_html/clients/texa/cpointcoriver/libs/:/home/cpointco/public_html/clients/texa/cpointcoriver/../phreeze/libs:/home/cpointco/public_html/clients/texa/cpointcoriver/vendor/phreeze/phreeze/libs/:.:/opt/alt/php55/usr/share/pear:/opt/alt/php55/usr/share/php') in /home/cpointco/public_html/clients/texa/cpointcoriver/libs/App/ExampleUser.php on line 5

Thank you...

**Comment by jasonhinkle** [comment]
Ah, ok.  You just need to put the phreeze libraries somewhere your app can find them.  You can do that by just putting the entire Phreeze directory in the same directory as your app which seems to be "/home/cpointco/public_html/clients/texa/".

You can alternatively edit the `_app_config.php` file and append the path where phreeze is located.

Basically the app just needs to find those files.

**Comment by maoaa** [comment]
Ok Jason,

It works fine now, thank you for your help...

**Comment by jasonhinkle** [comment]
Great!

**Comment by yure777** [comment]
Hello, I'm ready with my project.
I did everything on my machine (localhost: 3306)
But I can not put it in hostinger
I'll give you everything you need and show me where I am going wrong.

Link: http://internacao.16mb.com/

_machine_config.php

<?php
/**
 * @package Internações HMU
 *
 * MACHINE-SPECIFIC CONFIGURATION SETTINGS
 *
 * The configuration settings in this file can be changed to suit the
 * machine on which the app is running (ex. local, staging or production).
 *
 * This file should not be added to version control, rather a template
 * file should be added instead and then copied for each install
 */

require_once 'verysimple/Phreeze/ConnectionSetting.php';
require_once("verysimple/HTTP/RequestUtil.php");

/** database connection settings */
GlobalConfig::$CONNECTION_SETTING = new ConnectionSetting();
GlobalConfig::$CONNECTION_SETTING->ConnectionString = "mysql.hostinger.com.br";
GlobalConfig::$CONNECTION_SETTING->DBName = "u402048145_dbrv";
GlobalConfig::$CONNECTION_SETTING->Username = "u402048145_dbrv";
GlobalConfig::$CONNECTION_SETTING->Password = "fernandes777";
GlobalConfig::$CONNECTION_SETTING->Type = "MySQL_PDO";
GlobalConfig::$CONNECTION_SETTING->Charset = "utf8";
GlobalConfig::$CONNECTION_SETTING->Multibyte = true;
// GlobalConfig::$CONNECTION_SETTING->BootstrapSQL = "SET SQL_BIG_SELECTS=1";

/** the root url of the application with trailing slash, for example http://localhost/internações hmu/ */
GlobalConfig::$ROOT_URL = RequestUtil::GetServerRootUrl() . 'http://internacao.16mb.com/internacao/';

/** timezone */
date_default_timezone_set('America/Sao_Paulo');
---------------------------------------------------------------------
_app_config.php

<?php
/**
 * @package Internações HMU
 *
 * APPLICATION-WIDE CONFIGURATION SETTINGS
 *
 * This file contains application-wide configuration settings.  The settings
 * here will be the same regardless of the machine on which the app is running.
 *
 * This configuration should be added to version control.
 *
 * No settings should be added to this file that would need to be changed
 * on a per-machine basic (ie local, staging or production).  Any
 * machine-specific settings should be added to _machine_config.php
 */

/**
 * APPLICATION ROOT DIRECTORY
 * If the application doesn't detect this correctly then it can be set explicitly
 */
if (!GlobalConfig::$APP_ROOT) GlobalConfig::$APP_ROOT = realpath("./");

/**
 * check is needed to ensure asp_tags is not enabled
 */
if (ini_get('asp_tags')) 
	die('<h3>Server Configuration Problem: asp_tags is enabled, but is not compatible with Savant.</h3>'
	. '<p>You can disable asp_tags in .htaccess, php.ini or generate your app with another template engine such as Smarty.</p>');

/**
 * INCLUDE PATH
 * Adjust the include path as necessary so PHP can locate required libraries
 */
set_include_path(
		GlobalConfig::$APP_ROOT . '/libs/' . PATH_SEPARATOR .
		GlobalConfig::$APP_ROOT . '/../phreeze/libs' . PATH_SEPARATOR .
		GlobalConfig::$APP_ROOT . '/vendor/phreeze/phreeze/libs/' . PATH_SEPARATOR .
		get_include_path()
);

/**
 * COMPOSER AUTOLOADER
 * Uncomment if Composer is being used to manage dependencies
 */
// $loader = require 'vendor/autoload.php';
// $loader->setUseIncludePath(true);

/**
 * SESSION CLASSES
 * Any classes that will be stored in the session can be added here
 * and will be pre-loaded on every page
 */
require_once "App/ExampleUser.php";
--------------------------------------------------------------------------------

PRINT my files and error: https://imageshack.com/i/plmqbo3Pp

**Comment by yure777** [comment]
Hello, I'm ready with my project.
I did everything on my machine (localhost: 3306)
But I can not put it in hostinger
I'll give you everything you need and show me where I am going wrong.

Link: http://internacao.16mb.com/

**_machine_config.php**

<?php
/**
 * @package Internações HMU
 *
 * MACHINE-SPECIFIC CONFIGURATION SETTINGS
 *
 * The configuration settings in this file can be changed to suit the
 * machine on which the app is running (ex. local, staging or production).
 *
 * This file should not be added to version control, rather a template
 * file should be added instead and then copied for each install
 */

require_once 'verysimple/Phreeze/ConnectionSetting.php';
require_once("verysimple/HTTP/RequestUtil.php");

/** database connection settings */
GlobalConfig::$CONNECTION_SETTING = new ConnectionSetting();
GlobalConfig::$CONNECTION_SETTING->ConnectionString = "mysql.hostinger.com.br";
GlobalConfig::$CONNECTION_SETTING->DBName = "u402048145_dbrv";
GlobalConfig::$CONNECTION_SETTING->Username = "u402048145_dbrv";
GlobalConfig::$CONNECTION_SETTING->Password = "fernandes777";
GlobalConfig::$CONNECTION_SETTING->Type = "MySQL_PDO";
GlobalConfig::$CONNECTION_SETTING->Charset = "utf8";
GlobalConfig::$CONNECTION_SETTING->Multibyte = true;
// GlobalConfig::$CONNECTION_SETTING->BootstrapSQL = "SET SQL_BIG_SELECTS=1";

/** the root url of the application with trailing slash, for example http://localhost/internações hmu/ */
GlobalConfig::$ROOT_URL = RequestUtil::GetServerRootUrl() . 'http://internacao.16mb.com/internacao/';

/** timezone */
date_default_timezone_set('America/Sao_Paulo');
---------------------------------------------------------------------
**_app_config.php**

<?php
/**
 * @package Internações HMU
 *
 * APPLICATION-WIDE CONFIGURATION SETTINGS
 *
 * This file contains application-wide configuration settings.  The settings
 * here will be the same regardless of the machine on which the app is running.
 *
 * This configuration should be added to version control.
 *
 * No settings should be added to this file that would need to be changed
 * on a per-machine basic (ie local, staging or production).  Any
 * machine-specific settings should be added to _machine_config.php
 */

/**
 * APPLICATION ROOT DIRECTORY
 * If the application doesn't detect this correctly then it can be set explicitly
 */
if (!GlobalConfig::$APP_ROOT) GlobalConfig::$APP_ROOT = realpath("./");

/**
 * check is needed to ensure asp_tags is not enabled
 */
if (ini_get('asp_tags')) 
	die('<h3>Server Configuration Problem: asp_tags is enabled, but is not compatible with Savant.</h3>'
	. '<p>You can disable asp_tags in .htaccess, php.ini or generate your app with another template engine such as Smarty.</p>');

/**
 * INCLUDE PATH
 * Adjust the include path as necessary so PHP can locate required libraries
 */
set_include_path(
		GlobalConfig::$APP_ROOT . '/libs/' . PATH_SEPARATOR .
		GlobalConfig::$APP_ROOT . '/../phreeze/libs' . PATH_SEPARATOR .
		GlobalConfig::$APP_ROOT . '/vendor/phreeze/phreeze/libs/' . PATH_SEPARATOR .
		get_include_path()
);

/**
 * COMPOSER AUTOLOADER
 * Uncomment if Composer is being used to manage dependencies
 */
// $loader = require 'vendor/autoload.php';
// $loader->setUseIncludePath(true);

/**
 * SESSION CLASSES
 * Any classes that will be stored in the session can be added here
 * and will be pre-loaded on every page
 */
require_once "App/ExampleUser.php";
--------------------------------------------------------------------------------

PRINT my files and error: https://imageshack.com/i/plmqbo3Pp
