### ISSUE TITLE
calling regular jquery

### ISSUE THREAD

**Issue by diegolaz** [jasonhinkle/phreeze#178]
I´m creating a form in a new view (template).

I´m trying to create a datepicker from a form and I get a javascript error 

Error: ReferenceError: $ is not defined

when ever I call the corresponding jquery. Is there a different whay of calling jquery withing a template/view page?

tried:
<code>
<script type="text/javascript">
	//$('.soloNum').filter_input({regex:'[0-9]'})
	$('#fecha').datepicker({});
</script>
</code>

and 

<code>
<script type="text/javascript">
	$( document ).ready(function() {
		$('#fecha').datepicker({});
	});
</script>
</code>

and 

<code>
<script type="text/javascript">
	$(function() {	
		$('#fecha').datepicker({});
	});
</script>
</code>

with no luck..always same error

**Comment by diegolaz** [comment]
sorry the codes where

$('#fecha').datepicker({});

and the same within docuemtn.ready function, both failed

**Comment by jasonhinkle** [comment]
If you're using the default generated code, it uses LABjs to load all the javascript libraries asynchronously, so jQuery is probably not loaded before your script is being hit.

You can either load your script using LABjs, or alternatively you can just get rid of LABjs altogether and load the javascript files normally.

**Comment by diegolaz** [comment]
thanks! will try that!
