### ISSUE TITLE
problem adding columns with clickable images in listview

### ISSUE THREAD

**Issue by diegolaz** [jasonhinkle/phreeze#180]
I'm adding two columns to a listview.
I already have disabled all the lines of the tr click event, in the <tablename>.js so now the modal edit popup doesnt show up any more, good this far.

The problem is the buttons never get clicked because the whole row is still being "hovered" (changes color and hand cursor) so there is something preventing my buttons action... is there a way to handle this new buttons?
I added this code in the document ready after page.init();
<code>
        $( ".btnVer" ).on( "click", function() {
            var id_ = $(this).attr("alt");

            alert("View details");

        });
        $( ".btnAnular" ).on( "click", function() {

            var id_ = $(this).attr("alt");

            alert("Delete");
        });
</code>

**Comment by diegolaz** [comment]
basically, I can add/edit row click actions, but If I add a button to a column, the row click is preventing any action from the button to be executed....

**Comment by diegolaz** [comment]
so, if anyone has the same issue, thanks to jakecigar from the jquery forums, I got to this solution, in the <table>.js , where it handles the row click I added, 

if (e.target.nodeName === "IMG") {
                    var idBorrar = $(e.target).attr("alt");
                    alert("Borrar id: " + idBorrar);
                    return;
                } 

and with that I handle the image action.

**Comment by jasonhinkle** [comment]
interesting. thanks for posting a solution!

**Comment by NexEng** [comment]
Thanks Diegolaz; I was playing with this a while back and never finished it. This will be handy!
