### ISSUE TITLE
add custom date filters

### ISSUE THREAD

**Issue by diegolaz** [jasonhinkle/phreeze#185]
Hello, so I wanted to add next to the search box 3 date filters....a datepicker that you can choose a date, a month select that shows the last 24 months (year-month as in 2015-01, etc) and a third one that shows the last five weeks (date ranges).
On the template I have 
$("#month").change(function() {
	//alert($(this).val());
	page.fetchParams.filter = $(this).val();
	page.fetchParams.page = 1;
         page.fetchViewFacturaitemXUsuarios(page.fetchParams);
});
$("#semana").change(function() {
	//alert($(this).val());
	page.fetchParams.filter = $(this).val();
	page.fetchParams.page = 1;
         page.fetchViewFacturaitemXUsuarios(page.fetchParams);
});

but instead of fetchParams.filter .... how can I create an equal o date range check there? Or I can only post and manage it on the controller?

Thanks!

**Comment by jasonhinkle** [comment]
well the "filter" variable is simply one that is used to pass data back to the controller, but there is nothing really magical about the name "filter" or anything.  So to put in a date range, you would probably be best to create new fetchParams like "startDate" and "endDate" which your control will set a value, and can then be read by the controller.

On the controller side, you will have to look for those variables and set the Query criteria params appropriately.

You could look at how the filter parameter works as an example, though.

**Comment by diegolaz** [comment]
Sorry I did not answer before. I ended up using auto post on the select element and doing the criteria by getting the posted value (date)
