### ISSUE TITLE
Documentation Translation to pt-BR

### ISSUE THREAD

**Issue by calheira** [jasonhinkle/phreeze#192]
Hi @jasonhinkle !

We would like to translate the tutorials and other documentation related content. Could you  provide the http://phreeze.com/phreeze/documentation/ site files in a repository or branch?

**Comment by jasonhinkle** [comment]
That sounds awesome!  The documentation source is actually in the main phreeze repo right here https://github.com/jasonhinkle/phreeze/tree/master/documentation
