### ISSUE TITLE
Intermittent 404 Error

### ISSUE THREAD

**Issue by arjunnaha** [jasonhinkle/phreeze#200]
Hi Jason,

I seem to have a 404 error, that comes up and then after a few minutes it works, then I get a 404.

In other 404 issues, it seems to be ModRewrite in the .htaccess file, but I don't understand how it could work intermittently.

Arjun

**Comment by jasonhinkle** [comment]
Hmm, are you on a windows server by chance?  I seem to remember something about problems with random 404s on IIS, but it's been a long time.  Otherwise, it is definitely odd.
