### ISSUE TITLE
Exporting to CSV

### ISSUE THREAD

**Issue by arjunnaha** [jasonhinkle/phreeze#201]
Hi Jason,

I have found the ExportUtility, but how do I use it?
I'm guessing you just can't run it!

Best Regards,
Arjun

**Comment by jasonhinkle** [comment]
Mainly we use this at my company to export a DataSet as an Excel workbook. It uses PEAR/PHPExcel to do the work.  It's fairly simple, you use it like this:

```php
$myObjects = $this->Phreezer->Query('MyObject',$criteria);
ExportUtility::OutputAsExcel($myObjects,$this->Phreezer);
```

There's some other parameters to control the filename and such, but it's pretty bare-bones.
