### ISSUE TITLE
Change session timeout

### ISSUE THREAD

**Issue by diegolaz** [jasonhinkle/phreeze#207]
I'm trying to change the session timeout to 20 minutes.... adding this to the global config file should work??

ini_set('session.gc_maxlifetime', 1200);
session_set_cookie_params(1200);

Thanks!

**Comment by jasonhinkle** [comment]
_app_config.php would probably be the best if you consider it to be an "app-wide" setting.  If you consider it to be a machine-specific setting then _machine_config.php would be better.

Just a note that not all hosts allow overriding these values here, they may not have an effect.  You can also change the settings in .htaccess as well - it may depend on the host though.

**Comment by diegolaz** [comment]
Thanks for the reply!
