### ISSUE TITLE
Showing other columns instead of foreign key column in generated app

### ISSUE THREAD

**Issue by raheelkhan** [jasonhinkle/phreeze#208]
I started using phreeze and created an application based on my database. So far its doing good. However due to to lack of documentation i am unable to figure out how to show custom columns in list views. 

For example i have a table mobile operators in which there is a foreign key country_id. Now in the application list view page. Its showing country id but i want to show country_name instead of country_id in mobile operators list view. 

Thanks

**Comment by jasonhinkle** [comment]
The training video #5 "Reporters" shows an example of how to do that: http://phreeze.com/phreeze/documentation/videos.php

There's a lot of ways to do it, but this is the way that is the most efficient as far as a single join query.

**Comment by raheelkhan** [comment]
Yes thats what i was looking for. Thanks
