### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by rodrigorojas** [jasonhinkle/phreeze#214]
anyone can explain how to enable/configure a functional debug on my phreeze application?

thx a lot

**Comment by jasonhinkle** [comment]
Are you looking for a REPL, or do you just mean a working debug environment?

**Comment by rodrigorojas** [comment]
Excuse me sir. O just wanna configure a simple debug environment... today, I'm using Eclipse with PDT. Do you have some documentationfor this?
Thank you
