### ISSUE TITLE
M2M Example #3 issue

### ISSUE THREAD

**Issue by PhilMDev** [jasonhinkle/phreeze#222]
First off, you've done a tremendous job with Phreeze!  Thank you for making it available.

In the third example of M2M (using a reporter) there's an error in the BookAuthorCriteria class.  The GetFieldFromProp function must be public since it's public in the parent class Criteria.

Thank you again!

PhilM

**Comment by jasonhinkle** [comment]
ah thanks for that, i just fixed that in the example code.
