### ISSUE TITLE
Database triggers

### ISSUE THREAD

**Issue by Denace** [jasonhinkle/phreeze#223]
Hello, I'm implementing a web app based on phreeze and i have some custom triggers that are supposed to execute when a user saves a record. I have two triggers a "before update" and "before Insert".
Problem is when i save values i get a "Error Executing SQL: Can't update table 'trip' in stored function/trigger because it is already used by statement which invoked this stored function/trigger."
Now i'd like someone to help identify what phreeze is calling during the databse update process so i can appropriately place my triggers

**Comment by jasonhinkle** [comment]
This video shows a way to do query debugging - it sounds like it might help for your situation: https://www.youtube.com/watch?v=rKXQkLc-4Kg

**Comment by Denace** [comment]
I checked out the video, seem like I only needed the refresher to get thinking. Thanks ;)
