### ISSUE TITLE
Many to many relations

### ISSUE THREAD

**Issue by luisdavim** [jasonhinkle/phreeze#24]
Does phreeze support many to many relations?

Can you provide some guidelines on how to use this?

**Comment by frontjack** [comment]
Hi jasonhinkle, how are you? I'm an information system student but I still have no experience with programming. I need to do a database job, but the work has to be presented with as an application, the teacher allowed us to use automatic creation tools so I thought about the phreeze. I would like to know if it is already possible to work with relationship between tables (4 relations or more), if yes how can I do this, can I do it manually? Thank you very much in advance! Best Regards Marcos Paulo.
Note: I used google translator.
