### ISSUE TITLE
Error Opening MySQL Database

### ISSUE THREAD

**Issue by y25ean** [jasonhinkle/phreeze#279]
Issue when trying to connect to a localhost server using MAMP in the phreeze builder.
Error Message:
DataAdapter (db-36518) Error Opening DB: mysql extension is not enabled on this server. (retry attempts: 0)
Any info on how to fix this? Thanks

**Comment by amandalemos** [comment]
Update php version to current or activate your extension: 
In windows just remove ";" before extension=php_mysql from yout php.ini
