### ISSUE TITLE
after instalation 

### ISSUE THREAD

**Issue by samucati** [jasonhinkle/phreeze#281]
What could be this mistake?

DataAdapter (db-10643) Error Opening DB: mysql extension is not enabled on this server. (retry attempts: 0)

#0 C:\wamp64\www\phreeze\libs\verysimple\DB\Reflection\DBConnection.php(102): DBEventHandler->Crash(1, 'DataAdapter (db...')
#1 C:\wamp64\www\phreeze\libs\verysimple\DB\Reflection\DBConnection.php(122): DBConnection->Connect()
#2 C:\wamp64\www\phreeze\libs\verysimple\DB\Reflection\DBConnection.php(161): DBConnection->RequireConnection(true)
#3 C:\wamp64\www\phreeze\libs\verysimple\DB\Reflection\DBSchema.php(48): DBConnection->Select('show tables')
#4 C:\wamp64\www\phreeze\libs\verysimple\DB\Reflection\DBSchema.php(35): DBSchema->Load()
#5 C:\wamp64\www\phreeze\builder\libs\Controller\AnalyzerController.php(59): DBSchema->__construct(Object(DBServer))
#6 C:\wamp64\www\phreeze\libs\verysimple\Phreeze\Dispatcher.php(161): AnalyzerController->Analyze()
#7 C:\wamp64\www\phreeze\builder\index.php(22): Dispatcher::Dispatch(Object(Phreezer), Object(SavantRenderEngine), '', NULL, Object(GenericRouter))
#8 {main}

**Comment by pilotoqurdi** [comment]
I have the same problem with OSX Mojave. Getting this done with MyQSL is the error that I get. 
As MySQL Driver is mysql_connect. How can I solve it?

DataAdapter (db-30481) Error Opening DB: mysql extension is not enabled on this server. (retry attempts: 0)

#0 /Library/WebServer/Documents/phreeze/libs/verysimple/DB/Reflection/DBConnection.php(102): DBEventHandler->Crash(1, 'DataAdapter (db...')
#1 /Library/WebServer/Documents/phreeze/libs/verysimple/DB/Reflection/DBConnection.php(122): DBConnection->Connect()
#2 /Library/WebServer/Documents/phreeze/libs/verysimple/DB/Reflection/DBConnection.php(161): DBConnection->RequireConnection(true)
#3 /Library/WebServer/Documents/phreeze/libs/verysimple/DB/Reflection/DBSchema.php(48): DBConnection->Select('show tables')
#4 /Library/WebServer/Documents/phreeze/libs/verysimple/DB/Reflection/DBSchema.php(35): DBSchema->Load()
#5 /Library/WebServer/Documents/phreeze/builder/libs/Controller/AnalyzerController.php(59): DBSchema->__construct(Object(DBServer))
#6 /Library/WebServer/Documents/phreeze/libs/verysimple/Phreeze/Dispatcher.php(161): AnalyzerController->Analyze()
#7 /Library/WebServer/Documents/phreeze/builder/index.php(22): Dispatcher::Dispatch(Object(Phreezer), Object(SavantRenderEngine), '', NULL, Object(GenericRouter))
#8 {main}

**Comment by boussou** [comment]
Answer is pretty clear " Opening DB: mysql extension is not enabled on this server. "

You did not activate the old mysql extension (functions like "mysql_connect", or make use of MYSQL_PDO (look at phreeze/libs/verysimple/DB/DataDriver).

It is a matter of settings in PHP.INI or in the app config.
