### ISSUE TITLE
http://192.168.32.10/phreeze/builder/analyze

### ISSUE THREAD

**Issue by fontesanta** [jasonhinkle/phreeze#286]
Hello everyone, after http://192.168.1.10/phreeze/builder/, which works fine, after the data is filled I have this error in the analyze
http://192.168.32.10/phreeze/builder/analyze
Not Found
The requested URL was not found on this server.
Apache / 2.4.29 (Ubuntu) Server at 192.168.1.10 Port 80

Ubuntu 18.04

Can you help?

**Comment by diaraujo13** [comment]
Did you find a solution for this? I got the same file not found erro
