### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by alexkwood** [jasonhinkle/phreeze#3]
Hello,

I cloned the phreeze git to my apache root

after inputing the parameters in phreeze/builder/index.php
and clicking on "Analyze Database" I get the following error

The requested URL /phreeze/builder/analyze was not found on this server.

Is there any other stuff/changes that needs to be done besides cloning the git repo.

Thanks,
Alex

**Comment by arianestolfi** [comment]
I'm getting the same error also, 
I'm on mac osx server, so my link would be
http://localhost/~USER/phreeze/builder/analyze
and Im getting 
http://localhost/phreeze/builder/analyze

Iv tryed to uncoment rewrite base to
         RewriteBase /~USER/
but still got the same error
my http.conf aparently is with mode rewrite on...

**Comment by jasonhinkle** [comment]
The "already defined" error is causes by having both the Phreeze library folder and the .phar file.  The easiest solution is to just remove the .phar file from the application. That should solve the issue.

**Comment by acorman** [comment]
Likewise getting "The requested URL /phreeze/builder/analyze was not found on this server." 

Per MAMP, mod_rewrite is enabled, and I set AllowOverride to All in every stanza of http.conf where it occurs, restarted Apache, no change. Looked at PHP and Apache error logs but don't see any errors logged - any other thoughts?
